### ISSUE TITLE
BERTScore

### ISSUE THREAD

**Issue by fawazsammani** [maximek3/e-ViL#1]
Hello and good work! 
May you kindly let me know the setup you use for calculating BERTScore? As reported in their repo [here](https://github.com/Tiiiger/bert_score ) there are many different setups for this. For example the model type, the use of idf and if so the weights, the hugging face version....etc.

Have you used the default: roberta-large_L17_no-idf_version=0.3.0(hug_trans=2.3.0)-rescaled  ?

I did not find my answer in your paper. That's why i'm asking here

Many Thanks!

**Comment by maximek3** [comment]
Thanks for your post and sorry for the late reply. This is the hashcode for our BERTScore: `distilbert-base-uncased_L5_no-idf_version=0.3.7(hug_trans=3.0.0)`.
