### ISSUE TITLE
Three answer choices for VCR human evaluation  

### ISSUE THREAD

**Issue by amarasovic** [maximek3/e-ViL#3]
Hi, I noticed that you present three answer options instead of four for the answer selection part in the human evaluation of VCR explanations. Was this done to simplify the evaluation? How do you choose which three options, perhaps 2 random from the 3 wrong options, and the correct answer?  Thanks for the information!

**Comment by maximek3** [comment]
Hey Ana, yes, you are right on both guesses. This was simply done to make better use of the workers' time and to be in line with the other two datasets.

**Comment by amarasovic** [comment]
Thank you!
