### ISSUE TITLE
Unable to overlay bounding boxes for VCR

### ISSUE THREAD

**Issue by shrutijpalaskar** [maximek3/e-ViL#6]
Hello,

Thank you for the detailed templates for human evaluation! I am trying to use your template for VCR explanation evaluation and am facing issues with bounding boxes not overlaying on the images in the HTML. I have the correct path to the metadata json on AWS along with the images added to the CSV. 

The order of inputs in the CSV is: impath_1,question_1,answer_1,rationale_1_i,rationale_1_j,metadata_1, ... (for 10 hits)

Do you have any ideas about where the issue might be? Any pointers on this would help! 

Would it be possible for you to share your CSV sample? It might help me debug. Thank you!

Shruti

**Comment by maximek3** [comment]
Hey, here is an example meta csv file that I used: [ma_vcr_meta.csv](https://github.com/maximek3/e-ViL/files/7949380/ma_vcr_FINAL4REAL_meta.csv). Hopefully it helps!
