### ISSUE TITLE
VQAX answer choices for human evaluation

### ISSUE THREAD

**Issue by shrutijpalaskar** [maximek3/e-ViL#7]
Hello,

In your mturk template for vqax explanation evaluation, there is also the answer evaluation part same as VCR and ESNLIVE. For VQAX, can you please tell me where you got the various answer choices from?

Thank you,
Shruti

**Comment by maximek3** [comment]
Hey, we always included the right answer and randomly sampled the remaining options from all the answers present in VQA-X.
